In [2]:
import pandas as pd

In [5]:
# 2 main datatypes
series = pd.Series(['BMW','Toyota','Honda'])

In [6]:
series

0       BMW
1    Toyota
2     Honda
dtype: str

In [7]:
# series = 1 dimensional

In [9]:
colours = pd.Series(['blue','read','yellow'])

In [10]:
colours

0      blue
1      read
2    yellow
dtype: str

In [14]:
# dataframes = 2 dimensional
car_data = pd.DataFrame({'care make':series,'Colour':colours})

In [16]:
car_data

  care make  Colour
0       BMW    blue
1    Toyota    read
2     Honda  yellow

In [11]:
# import data 
df = pd.read_csv('car-sales.csv')

In [12]:
df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [27]:
# exporting dataframe
df.to_csv('exported_car_sales.csv',index=False)

In [28]:
exported_car_sales = pd.read_csv('exported_car_sales.csv')

In [29]:
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [3]:
disease_table = pd.read_csv('https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv')

In [4]:
disease_table

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:
df.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

## Describe data

In [13]:
# attribute
df.dtypes

# function
df.to_csv()

',Make,Colour,Odometer (KM),Doors,Price\n0,Toyota,White,150043,4,"$4,000.00"\n1,Honda,Red,87899,4,"$5,000.00"\n2,Toyota,Blue,32549,3,"$7,000.00"\n3,BMW,Black,11179,5,"$22,000.00"\n4,Nissan,White,213095,4,"$3,500.00"\n5,Toyota,Green,99213,4,"$4,500.00"\n6,Honda,Blue,45698,4,"$7,500.00"\n7,Honda,Blue,54738,4,"$7,000.00"\n8,Toyota,White,60000,4,"$6,250.00"\n9,Nissan,White,31600,4,"$9,700.00"\n'

In [14]:
df.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [15]:
car_columns = df.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [17]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [19]:
df.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [21]:
df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [22]:
car_prices = pd.Series([30000,50000,16000])
car_prices.mean(numeric_only=True)

np.float64(32000.0)

In [23]:
df.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [24]:
df['Doors'].sum()

np.int64(40)

In [25]:
len(df)

10

In [26]:
students = pd.Series(['Bekhzod','Ramz','Muhammad'])

In [27]:
grades = pd.Series([5,4,3])

In [28]:
students.data = pd.DataFrame({'students':students,'grades':grades})
students.data

   students  grades
0   Bekhzod       5
1      Ramz       4
2  Muhammad       3

## Viewing and selecting data

In [30]:
df.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [31]:
df.head(3)

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [32]:
df.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [33]:
df.tail(3)

     Make Colour  Odometer (KM)  Doors      Price
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [37]:
# .loc and .iloc
animals = pd.Series(['cat','dog','fish','hamster'],index = [0,3,4,10])

In [38]:
animals

0         cat
3         dog
4        fish
10    hamster
dtype: str

In [40]:
# .loc refers to index
animals.loc[3]

'dog'

In [43]:
animals.loc[10]

'hamster'

In [44]:
df.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [45]:
# .iloc refers to position
animals.iloc[3]

'hamster'

In [46]:
df.iloc[5]

Make                Toyota
Colour               Green
Odometer (KM)        99213
Doors                    4
Price            $4,500.00
Name: 5, dtype: object

In [47]:
animals.iloc[:3]

0     cat
3     dog
4    fish
dtype: str

In [48]:
df.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [49]:
df.head(4)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [50]:
df['Make']

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: str

In [51]:
df['Colour']

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: str

In [54]:
## They will show the same output
df.Make
df["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: str

In [55]:
df['Odometer (KM)']

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [56]:
## this will give an error:
df.Odometer (KM) # because there is space between them

AttributeError: 'DataFrame' object has no attribute 'Odometer'

In [57]:
df[df['Make'] == 'Toyota']

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [59]:
df[df['Odometer (KM)'] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00