## Dot product example

In [2]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
np.random.seed(0)
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [9]:
# create weekly_sales  DataFrame
weekly_sales = pd.DataFrame(sales_amount,index=['Mon','Tue','Wed','Thu','Fri'],columns=['Almond Butter','Peanut butter','Cashew butter'])

In [10]:
weekly_sales

     Almond Butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [11]:
# Calculate prices array
prices = np.array([10,8,12])

In [13]:
#create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),index=['Prices'],columns=['Almond Butter','Peanut butter','Cashew butter'])
butter_prices

        Almond Butter  Peanut butter  Cashew butter
Prices             10              8             12

In [15]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [16]:
# Shapes aren't aligned ,let's transpose
total_sales = prices.dot(sales_amount.T)

In [17]:
total_sales

array([240, 138, 458, 232, 142])

In [18]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [19]:
prices

array([10,  8, 12])

In [ ]:
#create daily sales

In [21]:
weekly_sales.T.shape

(3, 5)

In [24]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [25]:
weekly_sales.shape

(5, 3)

In [23]:
# doesnt work because they dont have equal rows
weekly_sales['Total $'] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total $

In [26]:
weekly_sales['Total ($)'] = daily_sales.T

In [27]:
weekly_sales

     Almond Butter  Peanut butter  Cashew butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142