In [1]:
import numpy as np
import pandas as pd

In [4]:
sales_amount = np.random.randint(30,size=(5,4))
sales_amount

array([[ 0,  6,  2, 15],
       [13, 20,  0, 16],
       [16,  9,  3, 27],
       [12,  6,  0,  2],
       [ 9, 24,  5,  4]])

In [5]:
weekly_sales = pd.DataFrame(sales_amount,index=['Mon','Tue','Wed','Thu','Fri'],columns=['DongFeng','TTZ','Bel','Lovol'])
weekly_sales

     DongFeng  TTZ  Bel  Lovol
Mon         0    6    2     15
Tue        13   20    0     16
Wed        16    9    3     27
Thu        12    6    0      2
Fri         9   24    5      4

In [8]:
prices = np.array([150,180,200,300])
prices

array([150, 180, 200, 300])

In [11]:
tractor_prices = pd.DataFrame(prices.reshape(1,4),index=['Prices'],columns=['DongFeng','TTZ','Bel','Lovol'])
tractor_prices

        DongFeng  TTZ  Bel  Lovol
Prices       150  180  200    300

In [12]:
total_prices = prices.dot(sales_amount.T)

In [13]:
total_prices

array([ 5980, 10350, 12720,  3480,  7870])

In [14]:
weekly_sales.T.shape

(4, 5)

In [15]:
daily_sales = tractor_prices.dot(weekly_sales.T)

In [16]:
daily_sales

         Mon    Tue    Wed   Thu   Fri
Prices  5980  10350  12720  3480  7870

In [17]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

     DongFeng  TTZ  Bel  Lovol  Total ($)
Mon         0    6    2     15       5980
Tue        13   20    0     16      10350
Wed        16    9    3     27      12720
Thu        12    6    0      2       3480
Fri         9   24    5      4       7870